version: '3'

services:
  # MySQL
  db:
    platform: 'linux/amd64'
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_m2
      MYSQL_USER: user01
      MYSQL_PASSWORD: compe
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 127.0.0.1:3306:3306

  # phpMyAdmin
  phpmyadmin:
    platform: 'linux/amd64'
    container_name: phpmyadmin_host
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8088:80
    